### ISSUE TITLE
sync: sntp tries to snyc with hostname salt

### ISSUE THREAD

**Issue by jan--f** [swiftgist/pillar-prototype#1]
Should probably be something widely available or better configurable in case cluster has no direct internet access.

**Comment by swiftgist** [comment]
I added this last minute and I think it needs to become generic for those that run something like chrony, systemd-timesyncd or disabled completely.  The sync should be put into its own sls file and add a pillar key such as timesync or something.  Also, the server "salt" should really be the default with an override from the pillar as well.

I'm not sure how to put a nice error message explaining that you need a properly configured time service, but these states need better messaging in general for failures.

**Comment by swiftgist** [comment]
These are done.  The question of whether time sync belongs inside or outside of the Ceph related states may still be in the air, but either way, it's configurable now.
