### ISSUE TITLE
permission issues with _get_minions_and_write_data

### ISSUE THREAD

**Issue by jschmid1** [swiftgist/pillar-prototype#10]
As salt-run presumably runs as user salt there should be a check in the method _get_minions_and_write_data that the directory /srv/pillar/ceph/cluster acutally belongs to salt:salt.

encountered this issue just now: 

`Exception occurred in runner bootstrap.selection: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 342, in low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/srv/modules/runners/bootstrap.py", line 59, in selection
    return _get_minions_and_write_data(selector, cluster, overwrite)
  File "/srv/modules/runners/bootstrap.py", line 93, in _get_minions_and_write_data
    with open(filename, 'w') as yml:
IOError: [Errno 13] Permission denied: '/srv/pillar/ceph/cluster/NODENAME.sls'`

was fixed by changing the ownership of the directory.

**Comment by jan--f** [comment]
I have encountered this problem too. Any dir a runner wants to write to must be owned by salt.
Maybe it is feasable to check for ownership at some point (or even on every run that wants to write) and give the user a better error message?
